Makefile
:warning: Don't this PR yourself :warning:
Depends on [#10](https://github.com/kuzzleio/sdk-c/pull/10)
Fix Makefile for android builds using environment variables for compilation toolchain tools such as CXX, CC, STRIP, AR ...
=> Fix Makefile for Android

include/collection.hpp, src/collection.cpp, test/features/step_definitions/collection-steps.cpp
Before the method `validateSpecifications` didn't take an index an a collection in parameters and could be used for any collection.  
This PR change the signature to match the rest of the collection controller. The method now take an index and a collection in addition to the specifications for this collection.
I also modify the `updateSpecifications` method. The method was taking an index and collection in parameter but it didn't scope the specifications to the collection. 
Related PR: https://github.com/kuzzleio/sdk-javascript/pull/318, https://github.com/kuzzleio/sdk-go/pull/211, https://github.com/kuzzleio/sdk-c/pull/13, https://github.com/kuzzleio/sdk-cpp/pull/11, https://github.com/kuzzleio/sdk-java/pull/13, https://github.com/kuzzleio/documentation-V2/pull/51
- Step 1: Run Kuzzle …
=> KZL-547 - Update validateSpecifications signature to take index and collection

.travis.yml, Makefile
Update CI to get:
*  `master` artifacts stored as `kuzzlesdk-cpp-$ARCH-$VERSION.tar.gz`
*  `*-dev` artifacts stored as `kuzzlesdk-cpp-$ARCH.tar.gz`
You cannot sorry :/
=> [ci] Change the name of S3 deployed artifact

CONTRIBUTING.md, align-submodules.sh
This PR add a script to align all submodules on the same branch.  
```
./align-submodules.sh
./align-submodules.sh 1-dev
```
- update contributing
=> Add script to align submodule on branch

.github/pull_request_template.md, include/realtime.hpp, src/realtime.cpp
The following are deprecated and will be removed in Kuzzle v2:
- `realtime:join` : useless method
- `realtime:list` : useless method
- `realtime:validate` : duplicate with `document:validate`
https://github.com/kuzzleio/sdk-c/pull/23 :arrow_left: :large_blue_circle:
- Step 1 : Make the sdk
- Step 2 :
- Step 3 :  
- Add optional template to link other sdk PRs
=> Remove realtime deprecated methods

CONTRIBUTING.md, Makefile, include/realtime.hpp, src/realtime.cpp
This PR remove the unused `index` and `collection` parameters for Realtime.Count
:arrow_left: https://github.com/kuzzleio/sdk-c/pull/21 :large_blue_circle: 
- add compile and run instructions
=> Fix realtime count arguments

include/server.hpp
Make QueryOptions in server controller adminExists method optionnal
Check Travis
=> [fix] Make QueryOptions in adminExists optionnal

Makefile
Add missing `sdk-c/build/kuzzle.h` to package archive 
Run : 
* `docker run --rm -it --privileged --network ci_default -e ARCH='amd64' -v "$(pwd)":/mnt kuzzleio/sdk-cross:openjdk8 make clean all`
* `docker run --rm -it --privileged --network ci_default -e ARCH='amd64' -v "$(pwd)":/mnt kuzzleio/sdk-cross:openjdk8 make package`
* Go to `deploy` folder and extract `*tar.gz` content.
* Check that `kuzzle.h` is present in `deploy/include` folder.
=> [fix] Add sdk-c/build/kuzzle.h to archive

test/features/step_definitions/document-steps.cpp
This PR adds some functional tests for `document`.`search` and its `next` method.
=> Kzl 642 functional tests

include/document.hpp, src/document.cpp
**:warning: do not merge**
**:warning: depends on https://github.com/kuzzleio/kuzzle/pull/1214**
Following https://github.com/kuzzleio/kuzzle/pull/1214, makes `document.count` `body` property optional.
https://github.com/kuzzleio/sdk-c/pull/30 :arrow_left: :large_blue_circle:
=> Kzl 832 document count body optional

src/kuzzle.cpp
Rename the cpp bridges because when using the C and CPP wrappers, those bridges had the same name so there was a conflict.
See travis
:arrow_right: https://github.com/kuzzleio/sdk-java/pull/25
=> [refactor] rename bridges

.gitignore, Makefile
The .tar.gz misses the `protocol.h` header from the C SDK. This makes anyone using our C++ SDK package get compilation errors.
To check if the problem is fixed: `make && make package` => check the .tar.gz file in the `deploy/` folder
Download the C++ SDK from the S3 server ([direct link](https://dl.kuzzle.io/sdk/cpp/1-dev/index.html) ), and inspect any archive: the file `protocol.h` is missing, but required by at least the `protocol.hpp` header file.
Add the `deploy` folder to the .gitignore file
=> Fix missing include in package

include/core.hpp
The `protocol.h` C header file is needed in multiple places in this SDK, yet it isn't included anywhere.
This PR fixes that.
=> Fix missing C header file in the C++ includes

include/protocol.hpp, include/websocket.hpp, src/kuzzle.cpp
As I was writting the documentation of the protocol interface I just thought it was useless to put getters in this interface (except for the getHost because it is used in the Kuzzle object) as developers can still implements getters in their class which inherit this Protocol interface (see websocket.cpp for instance).
See travis.
=> Remove getters in protocol interface

include/protocol.hpp, include/websocket.hpp, src/kuzzle.cpp, src/websocket.cpp
Change the behavior of Protocol::connect() and Protocol::close() to make them throws in case of error.
=> Make connect() and close() throws instead of returning a string

include/internal/exceptions.hpp, include/kuzzle.hpp, src/auth.cpp, src/collection.cpp, src/document.cpp, src/index.cpp, src/kuzzle.cpp, src/realtime.cpp, src/server.cpp, src/websocket.cpp
:warning: depends on https://github.com/kuzzleio/sdk-c/pull/46 :warning: 
This is a stabilization PR, aiming to fix some of the memory issues we have with this SDK:
* The static Kuzzle exception throwing method has been changed: it should not deallocate the memory of the structure provided to it. It now only throws the appropriate exception.
* A new `KUZZLE_API` macro has been added: it DRYifies and standardizes the way the Kuzzle API is requested, and how errors are handled. The main purpose of that macro is to correctly free the C result struct before throwing an exception
* All controller actions now use the new KUZZLE_API macro
* Fix some controller actions using `delete` to free the C result struct, instead of the corresponding C destructor
Note: there are other obvious memleaks …
=> Fix #37: standardize error handling and call the C destructors

.travis.yml, Makefile, README.md, run-tests.sh, test/features/step_definitions/CMakeLists.txt, test/features/step_definitions/cucumber.wire, test/features/step_definitions/kuzzle-sdk-steps.cpp, test/features/step_definitions/realtime-steps.cpp, test/valgrind.cgosdk.supp, test/valgrind.godeps.supp, test/valgrind.goruntime.supp
:warning: depends on https://github.com/kuzzleio/sdk-cross/pull/1 to make tests pass (we need the valgrind package in the docker test images) :warning: 
Add [valgrind](http://valgrind.org/) on top of functional tests, automatically generating a report available at the following path: `test/_build_cpp_tests/valgrind_report.log`
Do not review any of the `*.supp` files: those are only rules asking valgrind to suppress detected issues. The aim of these files, at least for now, is only to suppress Go and CGo errors (see below).
Go and CGo issues detected by valgrind are irrelevant. If needed, dedicated profiling should be performed directly on those layers instead.
The valgrind report should hide most, if not all, Go and Cgo errors, thanks to the `valgrind.*.supp` suppression files stored in …
=> Add valgrind to functional tests

include/internal/auth.hpp, include/internal/user_right.hpp, src/auth.cpp, src/user_right.cpp, test/features/step_definitions/steps.hpp
Compatibility update to make this SDK usable by SWIG:
- the new `UserRight` class needs a default constructor
- the `auth:getMyRights` method no longer return a vector of unique_ptr pointers, as this triggers [a SWIG bug](https://github.com/swig/swig/issues/558), with no known workaround. Instead, shared_ptr pointers are returned
=> SWIG compatibility update

include/internal/auth.hpp, include/internal/collection.hpp, include/internal/document.hpp, include/internal/index.hpp, include/internal/realtime.hpp, include/internal/server.hpp, src/auth.cpp, src/collection.cpp, src/document.cpp, src/index.cpp, src/kuzzle.cpp, src/realtime.cpp, src/server.cpp
Instead of getting the Go controllers from the Kuzzle object, and pass it to controllers while instantiating them, this PR makes the C++ controllers get their Go counterpart themselves.
This has the following benefits:
* regroup the memory allocation/deallocation in the same place
* make it easier to track with what a pointer has been allocated, and use the correct deallocator method (i.e. fix valgrind reports of pointers being deallocated with "delete" instead of "free")
* get rid of unused constructors
* simplify the C++ controllers generation process
=> Controllers allocate their own memory

include/internal/auth.hpp, include/internal/collection.hpp, include/internal/document.hpp, include/internal/index.hpp, include/internal/realtime.hpp, include/internal/search_result.hpp, include/internal/server.hpp, include/kuzzle.hpp, include/websocket.hpp, src/auth.cpp, src/collection.cpp, src/document.cpp, src/index.cpp, src/kuzzle.cpp, src/realtime.cpp, src/search_result.cpp, src/server.cpp, src/websocket.cpp, test/features/step_definitions/collection-steps.cpp, test/features/step_definitions/document-steps.cpp, test/features/step_definitions/kuzzle-sdk-steps.cpp, test/features/step_definitions/kuzzle_utils.cpp, test/features/step_definitions/realtime-steps.cpp
Use multi signature methods instead of having default arguments.  
All methods takes a `const query_options&` instead of a `query_options*`. Same for `room_options`, `kuzzle_request` and `options`.
Documentation: https://github.com/kuzzleio/documentation-V2/pull/206
- Step 1 : Run tests
- Add const qualifier in SearchResult
=> KZL-972 - Use multi signatures instead of default arguments

include/internal/exceptions.hpp, src/kuzzle.cpp, test/features/step_definitions/auth-steps.cpp, test/features/step_definitions/collection-steps.cpp, test/features/step_definitions/document-steps.cpp, test/features/step_definitions/index-steps.cpp, test/features/step_definitions/kuzzle-sdk-steps.cpp, test/features/step_definitions/kuzzle_utils.cpp, test/features/step_definitions/realtime-steps.cpp
Adds a `status()` getter for exceptions so we can use them in sdks generated by SWIG (c# for example)
- Declare everything in header and use `class` keyword
=> Add status getter for exceptions

include/internal/options.hpp, include/kuzzle.hpp, include/websocket.hpp, src/kuzzle.cpp, src/options.cpp, src/websocket.cpp
Using the C++ SDK in its current state results in programs hanging up while loading the SDK library.
The hangup is caused by the `defaultOptions` static, invoking the `Options` default constructor which, in turn, uses CGo.
Since that variable is static, it is initialized during the library load, before CGo has a chance to finish initializing its threads and mutexes. This results in a deadlock (see this related issue: https://github.com/golang/go/issues/26184 )
This PR fixes that issue by removing the need of a static "default options" variable. 
To do so, we need the Options `c_opts` method, which converts the C++ Options class into its equivalent `options` C struct, to be constant. This allows the use of delegating constructors without the need of a pre-allocated default Options …
=> Fix CGo Deadlock

src/event_emitter.cpp
Fix a crash caused by one-time event emitters, because an iterable was compared against the wrong map iterator. :sweat:
=> Bugfix: wrong iterator used

include/internal/search_result.hpp
Remove useless class SpecificationSearchResult
=> Remove useless class SpecificationSearchResult

include/protocol.hpp, src/protocol.cpp
:warning:  depends on https://github.com/kuzzleio/sdk-c/pull/55 :warning: 
The `kuzzle_event_listener` type is a typedef of a function pointer. Many bridges functions erroneously used the `kuzzle_event_listener*` type, meaning that they were taking a pointer over a variable storing a function pointer, meaning that dereferencing will not yield to a callable function (not mentioning the address becoming invalid as soon as the referenced variable becomes out of scope)
=> Fix erroneous pointer of function pointer

include/internal/event_emitter.hpp, include/kuzzle.hpp, include/protocol.hpp, src/event_emitter.cpp, src/protocol.cpp
Fix a various incompatibilities/errors when using this SDK with SWIG:
* `std::unordered_map` is unsupported by old Android SDKs: using this class with Android APIs 19&21 leads to obscure errors about a Hash class being undeclared
* `kuzzle.hpp` still showed a `getListeners` method but, as it was obsolete, its implementation was removed a few commits ago. Having it still there forces SWIG to generate a wrapper referencing an unknown method in the C++ library
=> SWIG compatibility fixes

include/protocol.hpp, include/websocket.hpp, src/protocol.cpp, src/websocket.cpp
As the title says: a new protocol has been added recently in the Go and Cgo layers, but not in the C++ one. 
When invoking certain methods such as the Kuzzle `playQueue` one, a crash occurs because the Cgo layer tries to invoke the non-existant C++ bridge.
Run the `playQueue` documentation test: it crashes without this fix, and it passes with it.
=> Add missing "isReady" protocol bridge

include/internal/core.hpp, include/kuzzle.hpp, test/features/step_definitions/auth-steps.cpp, test/features/step_definitions/collection-steps.cpp, test/features/step_definitions/document-steps.cpp, test/features/step_definitions/index-steps.cpp, test/features/step_definitions/kuzzle-sdk-steps.cpp, test/features/step_definitions/kuzzle_utils.cpp, test/features/step_definitions/kuzzle_utils.h, test/features/step_definitions/realtime-steps.cpp, test/features/step_definitions/steps.hpp
:warning: depends on https://github.com/kuzzleio/sdk-c/pull/58
Some classes or functions are made available without having to access the kuzzleio namespace.
This is mainly because of [this line](https://github.com/kuzzleio/sdk-c/blob/1-dev/include/internal/sdk_wrappers_internal.h#L19) and because the current Cgo headers do not allow an easy way to isolate these functions in a namespace.
This PR:
* applies the related Cgo patch
* remove all global `using namespace` instructions in tests to prevent them from hiding namespacing problems (as was the case until this change)
* use string litterals in tests 
Simply play the example shown in our [C++ getting started page](https://docs.kuzzle.io/sdk-reference/cpp/1/getting-started/):
* without this PR: the example code compiles just fine …
=> Properly isolate SDK objects in the kuzzleio namespace

include/kuzzle.hpp, src/kuzzle.cpp
After putting the offline queue management from `Protocol` to `Kuzzle` we forgot to add some getters.
This PR add the following getters:
- bool autoQueue() const noexcept;
- bool autoReconnect() const noexcept;
- bool autoResubscribe() const noexcept;
- bool autoReplay() const noexcept;
- int queueMaxSize() const noexcept;
- int queueTTL() const noexcept;
- int replayInterval() const noexcept;
- int reconnectionDelay() const noexcept;
Changed getters name to follow proper C++ naming convention.
=> Add missing getters about offline queue

include/kuzzle.hpp, src/kuzzle.cpp
* the `jwt` and `volatiles` getters in the Kuzzle object returned constant references of temporary variables, which makes the SDK crash whenever we try to access them
* these getters are wrappers for the cgo getters, which allocate memory on the heap: there was a memleak since the memory was never freed
* signature change: because of the 2 points above, these 2 getters either cannot be const, or they cannot return a const reference. I chose to drop the latter: it seems more important to me that getters claim to not change the state of a class, even if it means returning a new string instance every time they are called
* the `jwt` setter was missing
=> Fix a memleak+crash from the jwt and volatiles getters
